--------------------------------------------------------
--  File created - Friday-December-22-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TP_ITEMS
--------------------------------------------------------

  CREATE TABLE "C##MIKE"."TP_ITEMS" 
   (	"ITEM_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ITEM_NAME" VARCHAR2(20 BYTE), 
	"ITEM_DESC" VARCHAR2(500 BYTE), 
	"ITEM_PRICE" NUMBER(6,2), 
	"ITEM_PICTURE" VARCHAR2(40 BYTE), 
	"ITEM_CATEGORY" VARCHAR2(40 BYTE), 
	"ITEM_ISACTIVE" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TP_ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "C##MIKE"."TP_ORDER_ITEMS" 
   (	"ORDER_ID" NUMBER, 
	"ITEM_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TP_ORDERS
--------------------------------------------------------

  CREATE TABLE "C##MIKE"."TP_ORDERS" 
   (	"ORDER_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER(*,0), 
	"ORDER_CC_NUMBER" NUMBER(*,0), 
	"ORDER_SEC_NUMBER" NUMBER(*,0), 
	"ORDER_ZIPCODE" NUMBER(*,0), 
	"STORE_ID" NUMBER, 
	"ORDER_PRETAX_REVENUE" NUMBER(*,2), 
	"ORDER_TAX_REVENUE" NUMBER(*,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TP_REVIEWS
--------------------------------------------------------

  CREATE TABLE "C##MIKE"."TP_REVIEWS" 
   (	"REVIEW_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER(*,0), 
	"ITEM_ID" NUMBER(*,0), 
	"REVIEW_TEXT" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TP_STORES
--------------------------------------------------------

  CREATE TABLE "C##MIKE"."TP_STORES" 
   (	"STORE_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STORE_NAME" VARCHAR2(30 BYTE), 
	"STORE_DESC" VARCHAR2(500 BYTE), 
	"STORE_ADDRESS" VARCHAR2(100 BYTE), 
	"STORE_PICTURE" VARCHAR2(40 BYTE), 
	"STORE_ADD_DESC" VARCHAR2(500 BYTE), 
	"STORE_NUMBERSTAFF" NUMBER(3,0), 
	"STORE_ZIPCODE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TP_USERS
--------------------------------------------------------

  CREATE TABLE "C##MIKE"."TP_USERS" 
   (	"USER_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_USERNAME" VARCHAR2(20 BYTE), 
	"USER_PASSWORD" VARCHAR2(20 BYTE), 
	"USER_GENDER" VARCHAR2(1 BYTE), 
	"USER_ADDRESS" VARCHAR2(100 BYTE), 
	"USER_PHONE" NUMBER(*,0), 
	"USER_EMAIL" VARCHAR2(40 BYTE), 
	"USER_ISADMIN" NUMBER(1,0) DEFAULT 0, 
	"USER_FIRSTNAME" VARCHAR2(20 BYTE), 
	"USER_LASTNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##MIKE.TP_ITEMS
SET DEFINE OFF;
Insert into C##MIKE.TP_ITEMS (ITEM_ID,ITEM_NAME,ITEM_DESC,ITEM_PRICE,ITEM_PICTURE,ITEM_CATEGORY,ITEM_ISACTIVE) values (1,'Plain Pie','A delicious classic that you should buy right now because reasons',13.5,'Images/item1.jpg','Pizza',1);
Insert into C##MIKE.TP_ITEMS (ITEM_ID,ITEM_NAME,ITEM_DESC,ITEM_PRICE,ITEM_PICTURE,ITEM_CATEGORY,ITEM_ISACTIVE) values (2,'Pepperoni Pie','Lets be honest here. This is what you came for. Forsake your diet and dive into this delcious pie!',16,'Images/item2.jpg','Pizza',1);
REM INSERTING into C##MIKE.TP_ORDER_ITEMS
SET DEFINE OFF;
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (2,1);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (2,2);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (3,1);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (3,2);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (4,2);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (5,1);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (6,2);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (7,1);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (8,2);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (9,1);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (10,2);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (11,1);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (20,1);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (21,1);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (22,2);
Insert into C##MIKE.TP_ORDER_ITEMS (ORDER_ID,ITEM_ID) values (23,1);
REM INSERTING into C##MIKE.TP_ORDERS
SET DEFINE OFF;
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (6,3,13213313,12321,123123,2,16,1.4);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (8,5,12312312,12312,123123,1,16,1.4);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (9,3,123,123123,123123,1,13.5,1.18);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (29,1,1234567890,123,12345,1,1,1);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (20,3,12312312,12321,123123,2,13.5,1.18);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (11,6,234234324,234234,234324,1,13.5,1.18);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (3,3,1123123,123123,1231231,1,29.5,2.58);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (10,3,1234,1234,12345,2,16,1.4);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (21,3,231545636,345654,45654,1,13.5,1.18);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (2,1,1231231,123123,231231,1,29.5,2.58);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (7,5,1231233,123123,123123,2,13.5,1.18);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (23,3,123123121,3123,12312,1,13.5,1.18);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (4,1,21321331,1231,123123,2,16,1.4);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (5,3,123213,123123,123213,1,13.5,1.18);
Insert into C##MIKE.TP_ORDERS (ORDER_ID,USER_ID,ORDER_CC_NUMBER,ORDER_SEC_NUMBER,ORDER_ZIPCODE,STORE_ID,ORDER_PRETAX_REVENUE,ORDER_TAX_REVENUE) values (22,3,53534535,345345,34534,2,16,1.4);
REM INSERTING into C##MIKE.TP_REVIEWS
SET DEFINE OFF;
Insert into C##MIKE.TP_REVIEWS (REVIEW_ID,USER_ID,ITEM_ID,REVIEW_TEXT) values (9,5,2,'Update: It''s still pretty good.');
Insert into C##MIKE.TP_REVIEWS (REVIEW_ID,USER_ID,ITEM_ID,REVIEW_TEXT) values (10,4,2,'As an alien, I respect a good pizza. This is a good pizza.');
Insert into C##MIKE.TP_REVIEWS (REVIEW_ID,USER_ID,ITEM_ID,REVIEW_TEXT) values (5,5,1,'It''s pretty good.');
Insert into C##MIKE.TP_REVIEWS (REVIEW_ID,USER_ID,ITEM_ID,REVIEW_TEXT) values (6,5,2,'Also pretty good.');
Insert into C##MIKE.TP_REVIEWS (REVIEW_ID,USER_ID,ITEM_ID,REVIEW_TEXT) values (4,4,1,'I''M AN ALIEN AND EVEN I LOVE THIS!!!');
REM INSERTING into C##MIKE.TP_STORES
SET DEFINE OFF;
Insert into C##MIKE.TP_STORES (STORE_ID,STORE_NAME,STORE_DESC,STORE_ADDRESS,STORE_PICTURE,STORE_ADD_DESC,STORE_NUMBERSTAFF,STORE_ZIPCODE) values (1,'Frankies Pizza','The Best Food In Town!','Bronx, NY','Images/location1.jpg','"The best ability is availability"',7,10023);
Insert into C##MIKE.TP_STORES (STORE_ID,STORE_NAME,STORE_DESC,STORE_ADDRESS,STORE_PICTURE,STORE_ADD_DESC,STORE_NUMBERSTAFF,STORE_ZIPCODE) values (2,'Papa Pizza','Old Fashioned Pizza Done Right!','Lower Manhattan, NY','Images/location2.jpg','Quality is our game.',8,10004);
REM INSERTING into C##MIKE.TP_USERS
SET DEFINE OFF;
Insert into C##MIKE.TP_USERS (USER_ID,USER_USERNAME,USER_PASSWORD,USER_GENDER,USER_ADDRESS,USER_PHONE,USER_EMAIL,USER_ISADMIN,USER_FIRSTNAME,USER_LASTNAME) values (2,'test','test','m','23 Mars Place',1234567890,'mike@mike.com',0,'Mike','Mike');
Insert into C##MIKE.TP_USERS (USER_ID,USER_USERNAME,USER_PASSWORD,USER_GENDER,USER_ADDRESS,USER_PHONE,USER_EMAIL,USER_ISADMIN,USER_FIRSTNAME,USER_LASTNAME) values (3,'mike','mike','m','mike',9239813231,'sdf@ad.asd',0,'mike','gabriel');
Insert into C##MIKE.TP_USERS (USER_ID,USER_USERNAME,USER_PASSWORD,USER_GENDER,USER_ADDRESS,USER_PHONE,USER_EMAIL,USER_ISADMIN,USER_FIRSTNAME,USER_LASTNAME) values (4,'ayy','ayy','m','23 Mars Lane',2146666666,'bob@aliensarerealandiamone.com',0,'Bob','Alien');
Insert into C##MIKE.TP_USERS (USER_ID,USER_USERNAME,USER_PASSWORD,USER_GENDER,USER_ADDRESS,USER_PHONE,USER_EMAIL,USER_ISADMIN,USER_FIRSTNAME,USER_LASTNAME) values (1,'admin','admin',null,'admin',1111111111,'admin@admin.adm',1,'admin','admin');
Insert into C##MIKE.TP_USERS (USER_ID,USER_USERNAME,USER_PASSWORD,USER_GENDER,USER_ADDRESS,USER_PHONE,USER_EMAIL,USER_ISADMIN,USER_FIRSTNAME,USER_LASTNAME) values (5,'newuser','newuser','m','123 NotAReal Drive',2121234567,'redelstein@bigcorp.co',0,'Reinhardt','Edelstein');
Insert into C##MIKE.TP_USERS (USER_ID,USER_USERNAME,USER_PASSWORD,USER_GENDER,USER_ADDRESS,USER_PHONE,USER_EMAIL,USER_ISADMIN,USER_FIRSTNAME,USER_LASTNAME) values (6,'neweruser','newuser','m','76567dassada',7987987987,'hkhb@kjnkn.ads',0,'Mike','Mike');
--------------------------------------------------------
--  DDL for Index SYS_C007397
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MIKE"."SYS_C007397" ON "C##MIKE"."TP_ITEMS" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDER_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MIKE"."ORDER_ITEMS_PK" ON "C##MIKE"."TP_ORDER_ITEMS" ("ORDER_ID", "ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007405
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MIKE"."SYS_C007405" ON "C##MIKE"."TP_ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007401
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MIKE"."SYS_C007401" ON "C##MIKE"."TP_REVIEWS" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007399
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MIKE"."SYS_C007399" ON "C##MIKE"."TP_STORES" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007395
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MIKE"."SYS_C007395" ON "C##MIKE"."TP_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TP_ITEMS
--------------------------------------------------------

  ALTER TABLE "C##MIKE"."TP_ITEMS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MIKE"."TP_ITEMS" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TP_ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "C##MIKE"."TP_ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_PK" PRIMARY KEY ("ORDER_ID", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TP_ORDERS
--------------------------------------------------------

  ALTER TABLE "C##MIKE"."TP_ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MIKE"."TP_ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TP_REVIEWS
--------------------------------------------------------

  ALTER TABLE "C##MIKE"."TP_REVIEWS" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MIKE"."TP_REVIEWS" ADD PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TP_STORES
--------------------------------------------------------

  ALTER TABLE "C##MIKE"."TP_STORES" MODIFY ("STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MIKE"."TP_STORES" ADD PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TP_USERS
--------------------------------------------------------

  ALTER TABLE "C##MIKE"."TP_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MIKE"."TP_USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
